apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: uzng-service-status
spec:
  releaseName: uzng-service-status
  targetNamespace: platform
  values:
    datadog:
      env: prod
    oidc:
      issuer: https://uniphore.us.auth0.com/.well-known/openid-configuration
