{{- if .Values.ingress.enabled }}
{{- $fullName := include "uzng-service-status.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "uzng-service-status.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: uzng-service-status-cors, uzng-service-status-claims, uzng-service-status-oidc
    {{- include "uzng-service-status.ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: kong
  {{- include "uzng-service-status.ingress.tls" . | nindent 2 }}
  rules:
    - host: {{ .Values.ingress.hostName }}.{{ .Values.ingress.domainName }}
      http:
        paths:
          - path: /uzng-service-status
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
