apiVersion: v1
kind: Service
metadata:
  name: {{ include "uzng-service-status.fullname" . }}
  labels:
    {{- include "uzng-service-status.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port | required "service.port required" }}
  selector:
    {{- include "uzng-service-status.selectorLabels" . | nindent 4 }}
