---
kind: Module
type: helm
name: uzng-service-status

serviceResource:
  kind: Deployment
  name: uzng-service-status
  containerModule: uzng-service-status-image

build:
  dependencies:
    - name: uzng-service-status-image

values:
  appMode: ${var.appMode}
  logLevel: ${var.logLevel}
  logTraceCaller: ${var.logTraceCaller}

  image:
    id: ${modules.uzng-service-status-image.outputs.deployment-image-id}

  replicaCount: ${var.replicas}
  autoscaling:
    enabled: ${var.autoscaling.enabled}

  ingress:
    hostName: api-${providers["kubernetes"].config.namespace.name}
    domainName: ${providers["kubernetes"].config.defaultHostname}

  datadog:
    env: dev-${replace(local.usernameLowerCase,'.','-')}
